```{r}
library(randomForest)
setwd("~/Documents/Data Mining/Final Project/")
train <- read.csv('train.csv');
test <- read.csv('test.csv');
words <- read.csv('words.csv');
users <- read.csv('users.csv')

words$X <- NULL;
rows <- is.na(words$Good.Lyrics)
words$Good.Lyrics[rows] <- words$Good.lyrics[rows];
words$Good.lyrics <- NULL;
words$OWN_ARTIST_MUSIC <- as.character(words$OWN_ARTIST_MUSIC);
words$OWN_ARTIST_MUSIC[substr(words$OWN_ARTIST_MUSIC, 2, 2) == 'o'] <- 'DK';
words$OWN_ARTIST_MUSIC[words$OWN_ARTIST_MUSIC == ""] <- 'DK';
words$OWN_ARTIST_MUSIC <- as.factor(words$OWN_ARTIST_MUSIC);
words$HEARD_OF[words$HEARD_OF == ''] <- 'Never heard of';
words$HEARD_OF[words$HEARD_OF == 'Ever heard music by'] <- 'Heard of and listened to music EVER';
words$HEARD_OF[words$HEARD_OF == 'Ever heard of'] <- 'Heard of';
words$HEARD_OF[words$HEARD_OF == 'Listened to recently'] <- 'Heard of and listened to music RECENTLY';
words$HEARD_OF <- droplevels(words$HEARD_OF);

words <- na.roughfix(words);

fixtimes <- function (x) {
  x <- as.character(x)
  x[x == 'Less than an hour'] <- '.5';
  x[x == 'More than 16 hours'] <- '18';
  x <- as.numeric(substr(x, 1, 2));
  return(x)
}
users$LIST_OWN <- fixtimes(users$LIST_OWN);
users$LIST_BACK <- fixtimes(users$LIST_BACK);

domerge <- function (data) {
  data$RowID <- 1:nrow(data);
  merged <- merge(data, words, all.x=T);
  merged <- merge(merged, users, by.x='User', by.y='RESPID', all.x=T)
  merged <- na.roughfix(merged);
  merged <- merged[order(merged$RowID),];
  merged$RowID <- NULL;
  return(merged);
}

trainfeats <- domerge(train)[,-4];
testfeats <- domerge(test);

cleaned <- list(trainfeats=trainfeats, testfeats=testfeats, ratings=train$Rating)
summary(cleaned)
save(cleaned, file = "cleaned.RData")
cleaned.training = cleaned[[1]]
cleaned.test = cleaned[[2]]
cleaned.rating = cleaned[[3]]
cleaned.data = data.frame(cleaned.training, cleaned.rating)
summary(cleaned.data)
```

Single Tree:
```{r}
library(tree)
data.tree = tree(cleaned.rating~.,cleaned.data)
summary(data.tree)
plot(data.tree)
text(data.tree, pretty = 0)
```

Random Forrest:
```{r}
set.seed(2)
train = sample(1:nrow(cleaned.data), 150000)
train.set = cleaned.data[train,]
test.set = cleaned.data[-train,]
rf = randomForest(cleaned.rating~., train.set, do.trace=T,sampsize = 20000, ntree=100)
rf
```

Boosted Trees:
```{r}
boost = gbm(cleaned.rating~., train.set, distribution = "gaussian", n.trees = 1000, shrinkage = 0.01,interaction.depth = 4, verbose = T)
boost.pred <- predict(boost, test.set, n.trees = 1000)
mean((boost.pred - test.set$cleaned.rating)^2)
summary(boost)
```

Special Random Forest:
```{r}
set.seed(123)
size <- sample(1:nrow(cleaned.training),100000)
train.data = cleaned.data[size,]
test.data = cleaned.data[-size,]

trainIndices <- c()
train <- c()
rfs <- c()
testIndices <- c()
test <- c()
preds <- c()
rmse <- c()

for(i in 1:50){
  trainIndices <- which(train.data$Artist==i-1)
  train <- train.data[trainIndices,]
  set.seed(123)
  rfs <- randomForest(train$cleaned.rating~., train, 
                      ntree=100, nodesize=10, importance=T)
  testIndices <- which(test.data$Artist==i-1)
  test <- test.data[testIndices,]
  preds <- predict(rfs, test)
  rmse[i] <- sqrt(mean(preds-test$cleaned.rating)^2)
}

```


EDA:
```{r}
masterData <- cleaned.data
masterData <- masterData[,-c(8:88, 94:114)]

artistMean <- aggregate(cleaned.rating~Artist, data=masterData, FUN="mean")

library(ggplot2)
artistRating <- data.frame(x=seq(0,49,1), y=round(artistMean$cleaned.rating,0))

ggplot(data=artistRating, aes(x=x, y=y)) + 
  geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=y), vjust=2.6, color="white", size=3.5) +
  geom_text(aes(label=x), vjust=-0.5, color="red", size=3.5) +
  xlab("Artist Id") + ylab("Average rating for all tracks") +
  ggtitle("Average ratings of artists") + theme_minimal() 




regionArtist <- aggregate(cleaned.rating~Artist+REGION, 
                          data=masterData, FUN="mean")
regionArt <- with(regionArtist, regionArtist[order(REGION, -cleaned.rating),])

regionRating <- data.frame(x=regionArt$REGION, 
                           y=round(regionArt$cleaned.rating,0), 
                           z=regionArt$Artist)
regionRating <- regionRating[c(2:4,10:12,56:58,106:108,159:161),]
regionRating <- data.frame(w=as.factor(c(rep(seq(1:3)))), regionRating)
```


